# Change these first
owner: Live-Story # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: [PROD] LiveStory Site
    url: https://www.livestory.nyc/
  - name: [DEV] LiveStory console-dev
    url: https://console-dev.livestory.io/#/login
  - name: [PROD] LiveStory console
    url: https://console.livestory.io/#/login
  - name: [PROD] api.livestory.io health
    url: https://api.livestory.io/admin/health
    expectedStatusCodes:
      - 200
  - name: [PROD]-api.livestory.io-health
    url: https://api.livestory.io/admin/health
    expectedStatusCodes:
      - 200
  - name: [PROD]-api.livestory.io-front
    url: https://api.livestory.io/front/health
    expectedStatusCodes:
      - 200
  - name: [PROD]-api.livestory.io-front
    url: https://api.livestory.io/front/health
    expectedStatusCodes:
      - 200
  - name: [PROD]-api.livestory.io-content
    url: https://api.livestory.io/content/health
    expectedStatusCodes:
      - 200
      
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://pbs.twimg.com/profile_images/1439943804023414784/0DlRTv6C_200x200.jpg
  name: LiveStory
  introTitle: "**LiveStory** Monitoring"
  introMessage: Status pages
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://live-story.github.io/status/
      
#       https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
